report_pre_thesis/src/index.tex

Based on supervisor feedback, 26th September.

Update report structure

---

report_pre_thesis/src/_preamble.tex
report_pre_thesis/src/index.tex

Also added feedback from supervisor.

Write new introduction, problem statement, and problem definition

---

report_pre_thesis/src/sections/introduction.tex

Here's my thoughts:
I'm editing the problem statement. We need to ensure that we clearly communicate _what_ the problem is.
Limited accuracy and robustness is a symptom of a problem. That's what we'll solve next semester.
This semester, we're solving the problem of _identifying_ the above problem(s). But we also _plan_ to propose improvements to the components.
Does the new formulation make sense with this in mind?

Clarify identify vs propose

---

report_pre_thesis/src/sections/methodology.tex

Some starting paragraphs on the experiments. Will need to add some more and possibly rewrite a bit once experiments have been performed.

Experiment section intro

---

baseline/ica/data_processing.py
baseline/ica/ica.py

Run ica average_datasets experiment

---

report_pre_thesis/src/sections/experiments.tex

add cross-validation results to report

---

report_thesis/src/glossary.tex
report_thesis/src/index.tex
report_thesis/src/sections/problem_definition.tex

The idea here is to write down our thoughts on the direction of this project in an informal manner.
Please keep this in mind when you review: less focus on wording & grammar, more focus on whether it accurately represents what we'd like to communicate as the project goals and approach.

[KB-107] Write problem definition draft

---

report_thesis/src/references.bib
report_thesis/src/sections/introduction.tex

Tried to make it more evident why the progression in Mars exploration happened the way it did and made the phrasing more clear.

[KB-130] Thesis introduction feedback corrections

---

report_thesis/src/references.bib
report_thesis/src/sections/multi-task-learning.tex
report_thesis/src/sections/related_work.tex

Reading guide:
- Is my argument for why this is interesting strong enough?
- Are there any potential benefits to this that I may have missed that you can see?

[KB-106] Multitask learning related work

---

report_thesis/src/sections/background.tex
report_thesis/src/sections/problem_definition.tex

Also did a little clean up of errors I spotted.
Not much to say: Does it look good?

[KB-226] Ensure target, sample and location correctly used

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

I started out by including formal and mathematical definitions of the optimization problem SVM and SVR aim to solve, but after reviewing it with @Ivikhostrup, I decided to cut it and lean more towards a less technical, more intuition-based explanation (in the interest of remaining succinct).
I have kept the formal parts in the pull request, but it is commented out. Please read those parts as well and let me know if you think they should be included or excluded.

[KB-185] Define SVR

---

report_thesis/src/glossary.tex
report_thesis/src/references.bib
report_thesis/src/sections/background.tex

Reading guide:
* Is it sufficiently described? I felt that including the maths of the different concepts, such as CDF, would make it unnecessarily convoluted and not helpful for the discussion.

[KB-251] Quantile Transform

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

Reading guide:
I tried to keep it somewhat concise and to the point without explaining too much of the maths. 
* Should I explain/show some of the kernel functions?

[KB-253] Description of kernel pca

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

[KB-248] MinMax Normalization

---

report_thesis/src/glossary.tex
report_thesis/src/sections/background.tex
report_thesis/src/sections/baseline_replica.tex
report_thesis/src/sections/introduction.tex
report_thesis/src/sections/methodology.tex
report_thesis/src/sections/problem_definition.tex

I have addressed all the feedback. 
Do you agree with the changes?

[KB-244] Supervisor Feedback

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

Reading guide:
* Is it okay to mix terms such as base model vs level-0 generalizers (this is the term used in the paper)
* I am unsure about the very last paragraph. I think its a nice summary, but I can also see why it might be redundant.

[KB-204] Stacked Generalization

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

Decided to give my own attempt at writing this section.
I've used multiple sources to simplify the section as much as I could. Please let me know if there is anything that is unclear.
I've cut off many of the details that involve the actual trees and how they affect the model.
**See my review comments for how I've merged the two sources & incorporate them in the section.**

[KB-264] Rewrite GBR

---

report_thesis/src/references.bib
report_thesis/src/sections/background.tex

Reading guide:
* What do you think of the reorg? Is it what we'd like it to be?
* I've written an introduction to the background section, the preprocessing section, for ensemble learning and linear & regularization models.
* However, I feel like an introduction to linear & regularization models seems a little.. Redundant in a way? I dont have much to say. Perhaps you have some ideas.

[KB-255] Reorganize background

---

report_thesis/src/sections/background/preprocessing/pca.tex

Simplified the explanation by giving a more intuitive description rather than writing half a page of math formulas.
I also changed the cite to the data mining concepts book, as my rewrite is based on this book's section on PCA.

Rewrite PCA

---

report_thesis/src/sections/background/linear_and_regularization_models/pls.tex

Rewrite PCR & PLS

---

report_thesis/src/sections/proposed_approach/model_selection.tex
report_thesis/src/sections/proposed_approach/proposed_approach.tex

Proposal for @Ivikhostrup regarding using what he wrote to motivate model selection as the intro for proposed approach in its entirety. 🙏

write proposal

---

report_thesis/src/references.bib
report_thesis/src/sections/related_work.tex

I removed the old sources we had regarding PCA. The justification for using these were weak as they were either unpublished papers or published in journals with bad reputation.
These new references fixes that.

[KB-270] Updated PCA sources

---

report_thesis/src/glossary.tex
report_thesis/src/references.bib
report_thesis/src/sections/background/index.tex
report_thesis/src/sections/background/linear_and_regularization_models/enet.tex
report_thesis/src/sections/background/linear_and_regularization_models/index.tex
report_thesis/src/sections/background/linear_and_regularization_models/lasso.tex
report_thesis/src/sections/background/linear_and_regularization_models/ols.tex
report_thesis/src/sections/background/linear_and_regularization_models/rigde_regression.tex
report_thesis/src/sections/proposed_approach/model_selection.tex
report_thesis/src/sections/related_work.tex

I wrote about Ordinary Least Squares first in order to explain ridge regression.
I also wrote a new introduction to the section and moved it in front of the ensemble methods section since linear and regularization models are simpler than ensemble.

[KB-281] [KB-282] [KB-283] Background: Define OLS regression, Ridge regression, LASSO and Elastic Net regression

---

report_thesis/src/sections/proposed_approach/model_selection.tex

All the models are regression models

Fix model selection issue in table

---

report_thesis/src/sections/experiments/index.tex
report_thesis/src/sections/experiments/inital_experiments/initial_experiment.tex
report_thesis/src/sections/experiments/optimization_experiment/optimization_experiment_design.tex

Rewrite intro to experiments & results
